
server: 
    port: ${apigatewayport:8080}

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - PUT

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    nonSecurePortEnabled: true
    securePortEnabled: false
    non-secure-port: ${server.port}
    instanceId: ${spring.application.name}:${random.value}