
server:
    port: ${inventoryPort:8088}
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.mfouad.*
 # profiles:
  #  active: n2
  application:
    name: inventory
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ecommerce
    username: sa
    password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    nonSecurePortEnabled: true
    securePortEnabled: false
    non-secure-port: ${server.port}
    instanceId: ${spring.application.name}:${random.value}

topic:
  name: productsCategoriesTopic
  id: 24343dg
  groupId: productsGroup
  partitions: 2