
server:
    port: ${categoriesPort:8082}

logging:
  file:
    path: D:/java/workspaces/spring4_learn/e-commerce-full/log

spring:
  application:
    name: categories-services
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ecommerce
    username: sa
    password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    nonSecurePortEnabled: true
    securePortEnabled: false
    non-secure-port: ${server.port}
    instanceId: ${spring.application.name}:${random.value}